### PR TITLE
Create moc-sso-client external secret

### PR DESCRIPTION
**Pull request by naved001**
closes https://github.com/CCI-MOC/ops-issues/issues/362

### CODE REVIEW

**Comment by larsks** [comment]
This `ExternalSecret` resource is correct, but the secret in AWS is not. What you have here will create a secret that looks like:

```
apiVersion: v1
data:
  clientSecret: <value of cluster/ocp-prod/moc-sso/clientsecret>
kind: Secret
metadata:
  name: moc-sso-client-secret
  namespace: openshift-config
type: Opaque
```

But if we look at that secret, we find that `<value of
cluster/ocp-prod/moc-sso/clientsecret>` is a JSON
document:

```
$ aws secretsmanager get-secret-value --secret-id cluster/ocp-prod/moc-sso/clientsecret | jq -r .SecretString
{"cluster/ocp-prod/moc-sso/clientsecret":"ABCDEFGH..."}
```

This would result in:

```
apiVersion: v1
data:
  clientSecret: '{"cluster/ocp-prod/moc-sso/clientsecret":"ABCDEFGH..."}'
kind: Secret
metadata:
  name: moc-sso-client-secret
  namespace: openshift-config
type: Opaque
```

...which is not what we want.  We get the correct secret if we create it like this:

```
$ aws secretsmanager create-secret \
  --name cluster/ocp-prod/moc-sso/clientsecret \
  --secret-string "ABCDEFGH..." \
  --tag Key=cluster,Value=ocp-prod
```

I've created a secret named `example/client-secret` like this, which gives us:

```
$ aws secretsmanager get-secret-value --secret-id example/client-secret
{
    "ARN": "arn:aws:secretsmanager:us-east-1:574733721584:secret:example/client-secret-4ls0tr",
    "Name": "example/client-secret",
    "VersionId": "df203025-d13a-457b-8d00-5b2a58608a65",
    "SecretString": "ABCDEFGH...",
    "VersionStages": [
        "AWSCURRENT"
    ],
    "CreatedDate": "2021-09-06T22:42:32.556000-04:00"
}
```

There are situations in which we may want the secret value to be a JSON document, but this probably isn't one of them. See https://blog.oddbit.com/post/2021-09-03-kubernetes-external-secrets/ for some discussion on that topic.

**Comment by naved001** [comment]
thanks for pointing that out. I fixed it now.

I fixed my test secret in aws, and the updated secret in ocp-prod was pretty much instant.

**Comment by naved001** [comment]
Another question, I already have the secret in kubernetes that I had created manually, should we delete that before merging this PR?

**Comment by larsks** [comment]
Yes, the External Secrets controller will refuse to delete or update a `Secret` that it did not create...but I don't think it matters if we delete it before or after the merge.

**Review by larsks — APPROVED** [review]

**Pull request merged**
