### PR TITLE
Increase the postgres database pvc

### PR DESCRIPTION
**Pull request by naved001**
It will expand the backing pvc which is supported by the storage class

### CODE REVIEW

**Comment by naved001** [comment]
```
naved@Naveds-MacBook-Pro moc-apps % oc exec -it netbox-pgha1-jvcn-0 -c database -- df -h |grep pgdata
/dev/rbd1       9.8G  9.8G  5.9M 100% /pgdata
naved@Naveds-MacBook-Pro moc-apps % oc exec -it netbox-pgha1-jvcn-0 -c database -- du -sh /pgdata/pg13_wal
9.7G	/pgdata/pg13_wal
naved@Naveds-MacBook-Pro moc-apps % oc exec -it netbox-pgha1-bc2z-0 -c database -- df -h |grep pgdata
/dev/rbd0       9.8G  9.8G     0 100% /pgdata
naved@Naveds-MacBook-Pro moc-apps % oc exec -it netbox-pgha1-bc2z-0 -c database -- du -sh /pgdata/pg13_wal
9.7G	/pgdata/pg13_wal
```

**Review by hakasapl — CHANGES_REQUESTED** [review]
Do we also need to increase the backup volume size? That is specified in the same file on line `50`. Currently it is `15G` so we should probably set it to `25G`?

**Comment by naved001** [comment]
@hakasapl the backup volume is using less than a Gig.

**Comment by hakasapl** [comment]
Okay, it really seems like there's something off with the postgres db. I'd suggest merging this and see what's going on then we can reduce the size again if we need to.

**Review by hakasapl — APPROVED** [review]

**Comment by naved001** [comment]
I cleared the `wal` using `pg_archivecleanup`. While that freed up a good chunk of space, the database is still not available. In any case, this PR does not solve the issue.

**Pull request closed without merging**
