### PR TITLE
[netbox] Add missing postgrescluster resource

### PR DESCRIPTION
**Pull request by larsks**
This should have been included in #66.

### CODE REVIEW

**Review by naved001 — APPROVED** [review]

**Comment by naved001** [comment]
did you mark this as draft on purpose?

**Comment by larsks** [comment]
> did you mark this as draft on purpose?

I did; I've noticed some weirdness between what is in the output of `kustomize build` and what is actually deployed on the cluster and I'm trying to figure out what's going on.

**Comment by larsks** [comment]
I think it was just a sync issue.

**Comment by larsks** [comment]
It wasn't a sync issue; it's a kustomize version issue.

**Pull request merged**
