### PR TITLE
Added postgresql database configuration

### PR DESCRIPTION
**Pull request by skanthed**
I need to install a Postgres database in the MOC environment. 

This is the [link](https://raw.githubusercontent.com/operate-first/curator/curator1.1/Documentation/config/postgresql/postgres-database-cfg.yaml) to the config file that we are using to deploy the database - https://raw.githubusercontent.com/operate-first/curator/curator1.1/Documentation/config/postgresql/postgres-database-cfg.yaml

I tried to put this config according to the structure of the GitHub repo that's been followed after discussion with @naved001 

Just need to know how the value like Postgres-user, password, or database name will be passed and where to put the config or env file for it.

### CODE REVIEW

**Comment by naved001** [comment]
@larsks what's the best way for @skanthed to proceed with this? Should we create the secrets in aws or would it make sense to give @skanthed access to the `koku-metrics-operator` namespace and then she could take it from there.

**Comment by larsks** [comment]
I think ideally we'd like folks to be able to use their own secret store. Let me take a look and see what our options are.

**Comment by skanthed** [comment]
@larsks If you get some time, Can you please update here with the options about how to pass variables here, should we create a secret or something else?

**Comment by larsks** [comment]
@naved001 @skanthed Upon reflection, this content doesn't need to be part of the moc-apps repository. We've already committed (#127, #128) the changes that require administrative access, which *do* need to live here, but everything else can handled outside of the moc-apps repository.  In other words, I think that:

- @skanthed should move this content to her own repository
- We should close this PR
- We should create whatever RBAC is necessary for @skanthed to access to the `koku-metrics` operator so she can deploy these manifests
 
We will create the necessary access control today.

**Comment by skanthed** [comment]
Yes. I have deployed it directly in a staging environment directly after getting access.
So, closing this PR.

**Pull request closed without merging**
