### PR TITLE
Removing earlier curator project and it's dependencies.

### PR DESCRIPTION
**Pull request by skanthed**

### CODE REVIEW

**Comment by naved001** [comment]
You should also remove references to this bundle from the ocp-staging kustomization file.

Also, just wanted to make sure you still wanted to keep the following

https://github.com/CCI-MOC/moc-apps/blob/master/cluster-scope/overlays/ocp-staging/kustomization.yaml#L6-L8

(I think yes, because those can be re-used)

**Comment by naved001** [comment]
@skanthed also, /assign doens't work on this repo. When you open a PR you can request reviews from the github UI on the right.

image

**Comment by skanthed** [comment]
Yes. Removed everything. I know but don't have that permission it doesn't show a button on my reviewer side.

**Comment by naved001** [comment]
> I know but don't have that permission it doesn't show a button on my reviewer side.

@skanthed ah, I see. I have invited you to the moc organization which should take care of that.

**Review by larsks — APPROVED** [review]
Looks fine.

**Pull request merged**
