### PR TITLE
Add subscription for nvidia gpu operator

### PR DESCRIPTION
**Pull request by naved001**
This subscribes to the ~~redhat marketplace (rhmp) version.~~ non-redhat-marketplace version

### CODE REVIEW

**Comment by larsks** [comment]
This looks fine to me. I would like to understand the difference between the "Marketplace" version of the operator vs. the non-"Marketplace" version. Have you found any docs on that?

**Review by larsks — APPROVED** [review]

**Comment by larsks** [comment]
This looks fine. Is there some sort of "entitlement certificate" we need to install in order for this to work?

**Comment by naved001** [comment]
I think you are right. We may have to use entitled builds as a workaround. Or I should open a ticket with redhat.

According this [redhat solution](https://access.redhat.com/solutions/5820151) it should have been fixed versions >  4.7.19, but I am seeing the same issues on our cluster running 4.8.9.

```
naved@naved-MS-7984:~$ oc logs nvidia-driver-daemonset-c69m9 |grep elf
+ echo 'Installing elfutils...'
Installing elfutils...
+ dnf install -q -y elfutils-libelf.x86_64 elfutils-libelf-devel.x86_64
Error: Unable to find a match: elfutils-libelf-devel.x86_64
```

Relevant bits from the redhat article

> Root Cause
> 
> This was fixed in OCP 4.7.21 (See the release notes - Requirements for nvidia GPU driver container for driver toolkit) and OCP 4.8 by adding gcc and the related utilities to the driver toolkit base image so that they don't have to be installed by the build scripts.
> 
> Prior to that, the workaround is to use an entitled build.
> 
> Red Hat CoreOS and RHEL pods are not provisioned with entitlements by default, so when the Nvidia operator tries to build the kernel modules so that it can install the drivers, it is unable to install the relevant development RPMs. The cluster has to be configured to use the entitlements when creating pods to resolve this. In short, the build failed as a side effect of basic requirements of fetching dependencies which needed entitlement certificates.

Also, stable channel installs version 1.6 of the operator. I tried both version 1.6 and 1.8, both of those failed at installing `elfutils-libelf-devel.x86_64` package.

**Comment by naved001** [comment]
I went ahead and opened a support case. 

https://access.redhat.com/support/cases/#/case/03029429

**Comment by naved001** [comment]
looks like we'll have to use entitled builds. I am going to merge this one, since this only creates the subscription

**Pull request merged**
